name: test-deploy-package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # modified from https://github.com/pypa/pip/blob/main/.github/workflows/ci.yml
  test-package:
    name: test / ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os: [Ubuntu]
        python:
          - "3.10"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Ubuntu dependencies
        if: matrix.os == 'Ubuntu'
        run: sudo apt-get install bzr

      - name: Install MacOS dependencies
        if: matrix.os == 'MacOS'
        run: brew install bzr

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install package
        run: poetry install

      - name: Install pytest
        run: pip install pytest

      - name: Install pytest
        run: pytest tests/
